name: Sample Workflow Using SHA Digest

on:
  workflow_run:
    workflows: ["CI for Node.js"]
    types:
      - completed

jobs:
  use_sha_digest:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Debug directory contents
      run: |
          ls -al ./artifacts
          pwd

    # - name: Create artifacts folder (if missing)
    #   run: |
    #     mkdir -p ./artifacts

    - name: Download SHA Digest Artifact
      run: |
       gh run download 7885789632 --artifact sha_digestttt --directory ./artifacts
      # run: |
      #   curl -sSfL \
      #     -o ./artifacts/sha_digestttt.zip \
      #     -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
      #     "https://api.github.com/repos/${{ github.repository }}/actions/runs/62/artifacts"
      #   unzip -qq -d ./artifacts ./artifacts/sha_digestttt.zip
      # uses: actions/download-artifact@v2
      # with:   
      #   name: sha_digestttt
      #   path: ./artifacts
      #   run-number: 62
          

    - name: Commit and Push Artifact
      run: |
        pwd
        git add ./  # Correct the filename if different
        git commit -m "Add artifact from workflow"
        git push
